export const popularItems = [
  {
    id: 20,
    name: "Premium Queen Bed",
    src: "media/products/bed2.webp",
    price: 999.99,
  },
  {
    id: 13,
    name: "Standard Microwave",
    src: "media/products/microwave1.webp",
    price: 80.99,
  },
  {
    id: 22,
    name: "Bedding Pack",
    src: "media/products/bedding.webp",
    price: 29.99,
  },
  {
    id: 4,
    name: "Coffee Table",
    src: "media/products/coffeeTable.webp",
    price: 149.99,
  },
  {
    id: 11,
    name: "Smart Fridge",
    src: "media/products/fridge1.webp",
    price: 1159.99,
  },
  {
    id: 10,
    name: "Ganymede Lamp",
    src: "media/products/lamp2.webp",
    price: 79.95,
  },
  {
    id: 45,
    name: "Outdoor Furniture Set",
    src: "media/products/outdoorFurniture.webp",
    price: 1299.99,
  },
  {
    id: 7,
    name: "Cord Fabric 2 Seater Sofa",
    src: "media/products/sofa1.webp",
    price: 349.99,
  },
];

export const items = [
  {
    id: 1,
    name: "All",
    link: "all",
    items: [],
  },
  {
    id: 2,
    name: "Home Décor",
    link: "home-decor",
    items: [
      {
        id: 1,
        name: "ComfortWood Chair",
        src: "/media/products/chair1.webp",
        price: 79.99,
      },
      {
        id: 2,
        name: "Aesthetic Chair",
        src: "/media/products/chair2.webp",
        price: 89.99,
      },
      {
        id: 3,
        name: "Leather Cushion Chair",
        src: "/media/products/chair3.webp",
        price: 119.99,
      },
      {
        id: 4,
        name: "Marble Coffe Table",
        src: "/media/products/coffeeTable.webp",
        price: 149.99,
      },
      {
        id: 5,
        name: "Elegant Oak Desk",
        src: "/media/products/desk1.webp",
        price: 249.99,
      },
      {
        id: 6,
        name: "Sleek Modern Desk",
        src: "/media/products/desk2.webp",
        price: 220.0,
      },
      {
        id: 7,
        name: "Cord Fabric 2 Seater Sofa",
        src: "/media/products/sofa1.webp",
        price: 349.99,
      },
      {
        id: 8,
        name: "Premium 2 Seater Sofa",
        src: "/media/products/sofa2.webp",
        price: 449.99,
      },
      {
        id: 9,
        name: "Classic Lamp",
        src: "/media/products/lamp1.webp",
        price: 54.99,
      },
      {
        id: 10,
        name: "Ganymede Lamp",
        src: "/media/products/lamp2.webp",
        price: 79.95,
      },
    ],
  },
  {
    id: 3,
    name: "Kitchen & Dining",
    link: "kitchen-and-dining",
    items: [
      {
        id: 11,
        name: "Smart Fridge",
        src: "/media/products/fridge1.webp",
        price: 1159.99,
      },
      {
        id: 12,
        name: "Stainless Steel Fridge",
        src: "/media/products/fridge2.webp",
        price: 779.99,
      },
      {
        id: 13,
        name: "Standard Microwave",
        src: "/media/products/microwave1.webp",
        price: 80.99,
      },
      {
        id: 14,
        name: "Flat Bed Microwave",
        src: "/media/products/microwave2.webp",
        price: 149.99,
      },
      {
        id: 15,
        name: "Stainless Steel Microwave",
        src: "/media/products/microwave3.webp",
        price: 120.0,
      },
      {
        id: 16,
        name: "Stainless Steel Toaster",
        src: "/media/products/toaster1.webp",
        price: 45.99,
      },
      {
        id: 17,
        name: "Standard Toaster",
        src: "/media/products/toaster2.webp",
        price: 32.99,
      },
      {
        id: 18,
        name: "Electric Kettle",
        src: "/media/products/kettle.webp",
        price: 27.99,
      },
    ],
  },
  {
    id: 4,
    name: "Bedroom & Bathroom",
    link: "bedroom-and-bathroom",
    items: [
      {
        id: 19,
        name: "Double Bed",
        src: "/media/products/bed1.webp",
        price: 849.99,
      },
      {
        id: 20,
        name: "Premium Queen Bed",
        src: "/media/products/bed2.webp",
        price: 999.99,
      },
      {
        id: 21,
        name: "Standard Single Bed",
        src: "/media/products/bed3.webp",
        price: 499.99,
      },
      {
        id: 22,
        name: "Bedding Pack",
        src: "/media/products/bedding.webp",
        price: 29.99,
      },
      {
        id: 23,
        name: "Silk Pillow",
        src: "/media/products/pillow.webp",
        price: 9.99,
      },
      {
        id: 24,
        name: "3 Towel Set",
        src: "/media/products/towel1.webp",
        price: 15.99,
      },
      {
        id: 25,
        name: "Towel Jumbo Pack",
        src: "/media/products/towel2.webp",
        price: 23.99,
      },
      {
        id: 26,
        name: "Bathroom Shelf",
        src: "/media/products/bathroomShelf.webp",
        price: 129.99,
      },
    ],
  },
  {
    id: 5,
    name: "Appliances",
    link: "appliances",
    items: [
      {
        id: 27,
        name: "Hair Dryer",
        src: "/media/products/hairDryer1.webp",
        price: 29.99,
      },
      {
        id: 28,
        name: "Saloon Pro Hair Dryer",
        src: "/media/products/hairDryer2.webp",
        price: 44.99,
      },
      {
        id: 29,
        name: "Standard Iron",
        src: "/media/products/iron.webp",
        price: 24.99,
      },
      {
        id: 30,
        name: "1400 Spin Washing Machine",
        src: "/media/products/washingMachine1.webp",
        price: 249.99,
      },
      {
        id: 31,
        name: "1100 Spin Washing Machine",
        src: "/media/products/washingMachine2.webp",
        price: 219.99,
      },
      {
        id: 32,
        name: "Humidifer",
        src: "/media/products/humidifier.webp",
        price: 19.99,
      },
      {
        id: 33,
        name: "4K Ultra HD TV",
        src: "/media/products/tv1.webp",
        price: 249.0,
      },
      {
        id: 34,
        name: "LED TV",
        src: "/media/products/tv2.webp",
        price: 29.99,
      },
    ],
  },
  {
    id: 6,
    name: "Cleaning & Organization",
    link: "cleaning-and-organization",
    items: [
      {
        id: 35,
        name: "Bin",
        src: "/media/products/bin.webp",
        price: 7.99,
      },
      {
        id: 36,
        name: "Standard Mop Set",
        src: "/media/products/mop1.webp",
        price: 17.99,
      },
      {
        id: 37,
        name: "Mop Set Plus Set",
        src: "/media/products/mop2.webp",
        price: 21.99,
      },
      {
        id: 38,
        name: "AutoCleaning Robot",
        src: "/media/products/roomba.webp",
        price: 799.99,
      },
      {
        id: 39,
        name: "Vacuum Cleaner",
        src: "/media/products/vacuumCleaner.webp",
        price: 99.99,
      },
      {
        id: 40,
        name: "Hangers Pack (5x)",
        src: "/media/products/bedding.webp",
        price: 9.99,
      },
      {
        id: 41,
        name: "Shoe Rack",
        src: "/media/products/shoeRack.webp",
        price: 25.00,
      },
    ],
  },
  {
    id: 7,
    name: "Outdoor & Garden",
    link: "outdoor-and-garden",
    items:[
      {
        id: 42,
        name: "Plastic Garden Pot",
        src: "/media/products/gardenPot1.webp",
        price: 4.99,
      },
      {
        id: 43,
        name: "Double Garden Pot",
        src: "/media/products/gardenPot2.webp",
        price: 8.99,
      },
      {
        id: 44,
        name: "Outdoor Sofa",
        src: "/media/products/outdoorSofa.webp",
        price: 899.99,
      },
      {
        id: 45,
        name: "Outdoor Furniture Set",
        src: "/media/products/outdoorFurniture.webp",
        price: 1299.99,
      },
      {
        id: 46,
        name: "Hanging Chair",
        src: "/media/products/hangingChair.webp",
        price: 139.99,
      },
    ]
  },
];
